---
galaxy_info:
  author: WALLIX Automation Team
  description: Device and service management for WALLIX Bastion
  company: WALLIX Group
  license: MPL-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - "bionic"
        - "focal"
        - "jammy"
    - name: Debian
      versions:
        - "stretch"
        - "buster"
        - "bullseye"
  galaxy_tags: []

dependencies:
  - role: wallix-auth
    when: wallix_api_host is defined
  - role: wallix-config
    when: wallix_api_host is defined
  - role: wallix-domains
    when: wallix_api_host is defined

collections:
  - ansible.posix
  - community.general
